### ISSUE TITLE
Static files directory is not copied to the right place when using virtualenv

### ISSUE THREAD

**Issue by andreyshipilov** [ludwiktrammer/django-tagging-autocomplete#13]
Hi, I might be wrong but I'm running Django through the virtualenv. Inside the virtualenv I do the usual

```
pip install django-tagging-autocomplete
```

The package is installed into "venv/python2.7/site-packages/tagging_autocomplete" but the static files directory is copied to "venv/tagging_autocomplete/static"

Tested on Mac OS X El Capitan, Windows 10 and Ubuntu 14.04.

Currently my only fix is to copy the files manually. But I don't think it's a right solution :)

**Comment by ludwiktrammer** [comment]
Thank you for the report. Do you think you would be able to work out the solution and make a pull request? I haven't been using the module recently to be honest.

**Comment by tezro** [comment]
To be honest I don't really know at which point the static dir is copied. If you know where to start, I'm happy to do that.

**Comment by ludwiktrammer** [comment]
It is copied by `distutils` based on information in the `setupy.py`. One of the possible solutions may be to simply rewrite `setup.py` to use `setuptools` instead of `distutils`.

**Comment by tezro** [comment]
Ok, I'll give it a go.
