### ISSUE TITLE
deprecation on patterns in urls on django 1.9

### ISSUE THREAD

**Issue by sandroden** [ludwiktrammer/django-tagging-autocomplete#14]
Hi,

urls.py as is now raises warning in django1.9 as it uses old style patterns. Would you consider to change it to be compliant with new style? If you don't care to keep compatibility with older django rel the fix would simply be:

from django.conf.urls import url
from tagging_autocomplete import views

urlpatterns = [
    url(r'^list$', views.list_tags, name='tagging_autocomplete-list'),
]

thanks 
sandro
*;-)

**Comment by ludwiktrammer** [comment]
Ok, done. Thank you for the report.
