### ISSUE TITLE
spaces in tags

### ISSUE THREAD

**Issue by sandroden** [ludwiktrammer/django-tagging-autocomplete#17]
Hi,

I would say I used spaces in tags in the past, but now I'm no longer able to do it.... is it any possible?
TIA
sandro
*:-)

**Comment by ludwiktrammer** [comment]
Isn't that a general `django-tagging` issue?

**Comment by sandroden** [comment]
Sorry, it isnt's even an issue now. I realized that my collegue put a variable to allow and disallow it in the widget he prepared. 

thanks
