### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by djjudas21** [ludwiktrammer/django-tagging-autocomplete#21]
Hi there. Please would you consider tagging a new release on PyPI? The current release [0.5.0](https://pypi.org/project/django-tagging-autocomplete/#history) on PyPI is from 2015 and lacks https://github.com/ludwiktrammer/django-tagging-autocomplete/commit/a34653ff67b22df79059c8fadbadf00524c557b9. Thanks!

**Comment by ludwiktrammer** [comment]
@djjudas21 Done. Would you be able to verify that it works as expected?

Thank you for bringing my attention to the issue.

**Comment by djjudas21** [comment]
@ludwiktrammer Thanks - I will try it now

**Comment by djjudas21** [comment]
Works great - thanks :+1:
